//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceSite.DAL.Entities
{
    using ECommerceSite.DAL.Entities.Models;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SketchyProductsEntities : DbContext
    {
        public SketchyProductsEntities()
            : base("name=SketchyProductsEntities")
        {
        }

        public virtual DbSet<ProductDetail> ProductDetails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    }
}
